import * as fs from "fs";
import * as path from "path";
import { fileURLToPath } from "url";
import { DataSource, ReleaseData, Change } from "./types.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

interface CategorizedFeature {
  id: string;
  section: string;
  introduced_in: string;
  product: string;
  change: string;
  learn_more_links: Array<{ text: string; href: string }>;
  quality_score: number;
  category: string;
  mapping_confidence: number;
}

interface CategorizedFile {
  version: string;
  categorized_at: string;
  categories: Record<string, CategorizedFeature[]>;
  statistics: {
    total_features: number;
    features_by_category: Record<string, number>;
  };
}

/**
 * Categorized Data Source
 * Loads pre-categorized features from JSON files generated by categoryMapper
 */
export class CategorizedDataSource implements DataSource {
  name = "Categorized Data";
  description = "Pre-categorized features from parsed documentation";

  private dataDir: string;

  constructor(dataDir?: string) {
    this.dataDir =
      dataDir || path.join(__dirname, "../../data");
  }

  async fetch(version: string): Promise<ReleaseData> {
    const filePath = path.join(this.dataDir, `${version}.categorized.json`);

    if (!fs.existsSync(filePath)) {
      throw new Error(`Categorized data file not found: ${filePath}`);
    }

    try {
      const content = fs.readFileSync(filePath, "utf-8");
      const data = JSON.parse(content) as CategorizedFile;

      // Convert categorized features to ReleaseData format
      const categories: Record<string, Change[]> = {};

      for (const [categoryName, features] of Object.entries(
        data.categories
      )) {
        categories[categoryName] = features.map((feature) => ({
          id: feature.id,
          title: feature.product,
          description: feature.change,
        }));
      }

      // Release dates (hardcoded mapping for known versions)
      const releaseDates: Record<string, string> = {
        "11.44": "2023-04-15",
        "11.46": "2023-08-20",
        "12.0": "2024-01-10",
        "14.0": "2024-06-01",
        "15.0": "2025-01-15",
      };

      const releaseDate = releaseDates[version] || new Date().toISOString();

      return {
        version,
        releaseDate,
        categories,
      };
    } catch (error) {
      const errorMsg = error instanceof Error ? error.message : String(error);
      throw new Error(
        `Failed to load categorized data for ${version}: ${errorMsg}`
      );
    }
  }

  /**
   * Check if categorized data exists for a version
   */
  hasData(version: string): boolean {
    const filePath = path.join(this.dataDir, `${version}.categorized.json`);
    return fs.existsSync(filePath);
  }

  /**
   * Get all available versions in categorized data
   */
  getAvailableVersions(): string[] {
    try {
      const files = fs.readdirSync(this.dataDir);
      return files
        .filter((f) => f.endsWith(".categorized.json"))
        .map((f) => f.replace(".categorized.json", ""));
    } catch {
      return [];
    }
  }
}
